drop table if exists line CASCADE;

drop table if exists line_station CASCADE;

drop table if exists station CASCADE;

create table line (
                      id bigint generated by default as identity,
                      color varchar(255),
                      distance bigint,
                      down_station_id bigint,
                      name varchar(255),
                      up_station_id bigint,
                      primary key (id)
);

create table line_station (
                              id bigint generated by default as identity,
                              line_id bigint not null,
                              station_id bigint not null,
                              primary key (id)
);

create table station (
                         id bigint generated by default as identity,
                         name varchar(20) not null,
                         primary key (id)
);
